### ISSUE TITLE
BC theme by default

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb#16]
**OP timer**

---

## This feature support the following requirements

[base-build](https://openplus.monday.com/boards/3958997205/pulses/4162765081)

## Additional context

Since Drupal is moving away from profiles, this cannot be enabled by default.

We need to make sure the theme looks correct no matter what settings are applied.

## Proposed solution

Try the various theme settings for the BB. Make sure they all look decent. Once that is done, for future projects, enable the theme and configure as needed.

## Estimated level of effort

- 2 days

## Definition of done (DoD)
- [ ] theme can be enabled on a clean install
- [ ] changing theme settings does not break the theme

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

**Comment by CraigClark** [comment]
@lkmorlan is this the sort of thing we should have automated tests for? Check that black text isn't on a grey background, that sort of thing?

**Comment by lkmorlan** [comment]
We can easily have a test that checks for what theme is enabled. But in principle, it should be possible to switch out the theme independent of everything else. Checking contrast is a different story. That requires different testing tools.
