### ISSUE TITLE
Content type for Documentation

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#18]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4614313836

---

>  **TBD** this is probably a base-build candidate. If so, how do we handle the content type? WxT has a 'book' content type that comes with it. We then use the same settings for project specific content that requires the book features.

## User story

As a user of any BD Drupal application, I want to be able to access documentation that will help me understand how the system works for a person with my role so that I can learn how to work with the system to accomplish the tasks it is designed to do.

As a manager of an application,  I want to create sets of documentation so that users of the system can easily find material relevant to how they work.

## This feature support the following requirements

[base-build](https://openplus.monday.com/boards/3958997205/pulses/4162765081)

## Additional context

This content type should use the book module. The book should support subway navigation for internal pages and an option to print the content of the entire book. See RSAMS for an example. 

A table of contents for sections within a page will be added in #22.

## Proposed solution

- Use the book module for this content type
- Content field should be the default body with summary
- Show summary expanded

## Estimated level of effort

- 3 days

## Definition of done (DoD)
1. - [x] Documentation is an index page with a table of contents of child pages at the bottom
2. - [x] The table of contents at the bottom of the index page shows a summary if it is available
3. - [x] The documentation has forward, home, and backward navigation 
4. - [x] People with correct permissions can add sub-pages directly from a page in the documentation 
5. - [x] There is a link to print all pages of the selected documentation
6. - [x] The title of the index page appears in the breadcrumb
7. - [x] A custom module exists `bcbb_book` that will enable book and create the content type

### Automated functional tests

- [x] I have written functional tests for this feature
- [x] I have run the functional tests and they pass

**Comment by CraigClark** [comment]
@lkmorlan don't worry about the subway nav if it's not included in the module. We can add it later, it's just CSS and we can write something that looks the same as WET but is more modern

**Comment by lkmorlan** [comment]
Examples:
https://dv12.openplus.ca/en/node/242
https://dv12.openplus.ca/en/help

**Comment by CraigClark** [comment]
This works fine, but needs theming. Adding myself to work on that.
