### ISSUE TITLE
Configure aliases so old ones are kept if the path changes

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#19]
**OP timer**

---

## This feature support the following requirements

[base-build](https://openplus.monday.com/boards/3958997205/pulses/4162765081)

## Proposed solution

at `/admin/config/search/path/settings`, select setting to keep existing alias when a path changes.

## Estimated level of effort

- less than 1 day

## Definition of done (DoD)
- [ ] _Create a new alias. Leave the existing alias functioning._ is set at `/admin/config/search/path/settings`

**Comment by CraigClark** [comment]
This is done for data catalogue, however it should be added to base build and brought back in.

**Comment by NicoledeGreef** [comment]
not working on this
