### ISSUE TITLE
Analytics Options Assessment and Inclusion in Base Build

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb#21]
**OP timer**

---

## This feature support the following requirements

As a business owner of a Drupal-based application
I need to have access to basic site analytics
so that I can assess the use of the site on demand.

## Additional context

Application owners are looking for:

- traffic reports (visitors, unique visitors?)
- what pages people are visiting
- how long they’re on the pages 
- what the entry and exit spots are for a session
- what pathways people take through the site
- what times and days the pages are being viewed
- what media library assets are being opened
- any other “industry standard” information available in analytics tools. The more granular we can get the better.

## Proposed solution

Analysis of options, ideally native to Drupal, that can support these types of analytics.  Timeline for advice and discussion: mid-August 2023

## Definition of done (DoD)
- [ ] options communicated to the base build project team
- [ ] discussion of the options
- [ ] possible inclusion of selection in the base build (OpenPlus)
- [ ] possible adoption of selection in the FINtranet app (MFIN-IMB)

**Comment by CraigClark** [comment]
@NicoledeGreef Drupal doesn't do any sort of analytics naively. Typically you would integrate a 3rd party tool. Google analytics is popular for public facing sites. We have set up Drupal to work with other tracking tools as well. IS there something BC uses internally already?

**Comment by chrislaick** [comment]
@NicoledeGreef I'm used to using Google Analytics, but research has shown me that Matomo is an on-premise alternative, where data ownership is important. There is mention of Matomo in the OpenShift tech docs:

- https://matomo.org/
- https://docs.developer.gov.bc.ca/reusable-services-list/#matomo-openshift
- https://developer.gov.bc.ca/Community-Contributed-Content/Matomo-OpenShift

**Comment by NicoledeGreef** [comment]
Google Analytics/Matomo thread: https://stackoverflow.developer.gov.bc.ca/questions/811/817#817

I notice that there is a Drupal module for Matomo as well that allows for Matomo tag management and settings changes through the Drupal Admin UI.  Not sure if it is compatible with Drupal 10.

**Comment by lkmorlan** [comment]
Drupal module `matomo` advertises that it is compatible with Drupal 10.

https://www.drupal.org/project/matomo

**Comment by NicoledeGreef** [comment]
@lkmorlan  - can you please do an assessment of the module? any red flags or concerns?

**Comment by lkmorlan** [comment]
The `matomo` Drupal module has just over 17,000 users. It has recent activity in the issue queue and in code commits. It is likely that this module works well.

**Comment by CraigClark** [comment]
Added to agenda for next base-build meeting #23

**Comment by CraigClark** [comment]
Closing as the assessment is done, how it gets added to the build will be discussed at a base-build meeting
