### ISSUE TITLE
Add search bar to header

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#24]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/4967667339

---

## This feature support the following requirements

[alpha release](https://openplus.monday.com/boards/3958997205/pulses/4605939234)

## Additional context

This change should be available in the base-build but needs to be implemented on the data catalogue.

If needed, the base-build theme is here https://github.com/bcgov/bcbb-theme

### Remove user menu currently in header
<img width="1373" alt="image" src="https://github.com/bcgov/bcbb/assets/3910508/290851d8-a322-4a49-8c10-4b7fb39aafa2">

### add search block to header
![header with search](https://github.com/bcgov/bcbb/assets/3910508/59bc5262-3daa-4d93-80a7-ec192de134ac)

> **Note**: The search block should not appear in the header on the search page (`/search/site`)

## Estimated level of effort

- 1 day
- 2 days
- 3 days
- 4 days
- 5 days

## Definition of done (DoD)
- [ ] User can search for content from any page on the site by using a search bar in the header
- [ ]The search block does not appear in the header on search page

### Automated functional tests

- [ ] I have written functional tests for this feature
- [ ] I have run the functional tests and they pass

**Comment by CraigClark** [comment]
Is it possible to have this as part of the `bcbb_search` module?

**Comment by gurjinder12** [comment]
It'll take 1 day LOE
