### ISSUE TITLE
Changes to theme for book module

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#27]
## Timer
https://openplus.monday.com/boards/4092908516/pulses/4994902277

## Layout

Please see screenshot.

If a template isn't practical for the links, we need 

```html
<a href="/node/add/book?parent=38">Add child page</a>
```
 to be 
```html
<a class="btn btn-light" href="/node/add/book?parent=38"><i class="fa-solid fa-print"></i> Add child page</a>
```

and

```html
<a href="/node/add/book?parent=38">Add child page</a>
``` 
should be 

```html
<a class="btn btn-success"> href="/node/add/book?parent=38">Add child page <i class="fa-solid fa-plus"></i></a>
```

<i class="fa-solid fa-print"></i>

![image](https://github.com/bcgov/bcbb/assets/3910508/ee44af3b-b62b-4cbd-926d-3afc0cd02e0f)

## Sidebar

Remove sidebar from home page of a book, these links are available at the bottom of the page. 

![Image](https://github.com/bcgov/bcbb/assets/3910508/3ba67f07-add6-44a8-801d-2930e4074420)

**Comment by lkmorlan** [comment]
Correct HTML for links
