### ISSUE TITLE
Investigation of mega menus

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb#29]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5064073819

---

Investigation of mega menu

**Comment by NicoledeGreef** [comment]
megaMenu blocks work/are desirable

weMegaMenu
tbMegaMenu

@chrislaick to test drive both and ideally choose one to be included in the base-build.

@craigClark to send @NicoledeGreef and @chrislaick instructions on how to add modules to the base-build

**Comment by CraigClark** [comment]
@chrislaick @NicoledeGreef 
Adding modules to the base build is pretty easy. See [*Adding modules*](https://github.com/bcgov/bcbb/wiki/Adding-modules) in the base-build wiki.

**Comment by chrislaick** [comment]
@CraigClark @NicoledeGreef 
The mega menu module we should do with is we_megamenu. We are currently using this module in our other project and it works well.

**Comment by NicoledeGreef** [comment]
@chrislaick to add we_megamenu to the bcbb

**Comment by chrislaick** [comment]
PR submitted: https://github.com/bcgov/bcbb/pull/44

**Comment by chrislaick** [comment]
PR merged. Closing this ticket.
