### ISSUE TITLE
SMTP module

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#37]
Timer

https://openplus.monday.com/boards/4092908516/pulses/5860518150

----

Add smtp to base-build, enable on DC and build.

**Comment by CraigClark** [comment]
Looks like we will need it for DC. I'll just have it added to BB

**Comment by chrislaick** [comment]
> @chrislaick SMTP is not in the base-build. We are not using it on the data catalogue, however it's a pretty common module.
> 
> Should it be in base-build?

I'm thinking yes it should be in base-build.

**Comment by lkmorlan** [comment]
Completed in January.
