### ISSUE TITLE
Gin Admin Theme and Gin Toolbar

### ISSUE THREAD

**Issue by chrislaick** [bcgov/bcbb#38]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/5931744953

---

Add gin theme and gin_toolbar module to the base build. Explore whether gin theme would play nice on DC.

**Comment by CraigClark** [comment]
@NicoledeGreef This has been added to the base-build. We turned it on on dv14 to verify it works. Screenshot below.

We are turning this of in the data catalogue for now. It's different than all the other sites we work on, we can be more efficient working in the default admin theme (claro). Later on, it will be easy to use Gin if you like, there's isn't much config. You just turn it on and it will work. Once we deploy to OpenShift, we can turn it on in dev so you can try it.



![Image](https://github.com/bcgov/bcbb/assets/3910508/18c9a67b-efa9-4382-9354-770701ff6d4f)
