### ISSUE TITLE
port devOps docs to new repo

### ISSUE THREAD

**Issue by NicoledeGreef** [bcgov/bcbb#40]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6459822055

---

Ensure devOps related documentation is written in a generic fashion (not app specific) and is universally accessible.

**Comment by NicoledeGreef** [comment]
see https://github.com/bcgov/bcbb-gitops-docs

**Comment by CraigClark** [comment]
@NicoledeGreef Are you still stuck on this?

**Comment by NicoledeGreef** [comment]
Thanks to @sylus who ported the updated docs to the new repo when he made his updates.
