### ISSUE TITLE
Reset buttons should have a danger class

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#46]
**OP timer**

https://openplus.monday.com/boards/4092908516/pulses/6732112688

---
Reset buttons should have class  `btn-danger` instead of `btn-primary`

Here is an example from the search page

<img width="1343" alt="image" src="https://github.com/bcgov/bcbb/assets/3910508/4937e426-615f-4c36-8b65-89c573e8d77b">

Here is an example from the report builder | dashboard > reports > report builder

<img width="1363" alt="image" src="https://github.com/bcgov/bcbb/assets/3910508/2a192389-ae64-4c95-ae51-3445ed363e82">

**Comment by NicoledeGreef** [comment]
reviewed in dv14
