### ISSUE TITLE
Write documentation for search module

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#8]
**OP timer**

---

## User story

As a product manager at MFIN, I want to be able to understand the deployment of a search feature to any Drupal project so that users can be confident they have accurate results and overhead is minimal for the development team.

## This feature support the following requirements

[base-build](https://openplus.monday.com/boards/3958997205/pulses/4162765081)

## Additional context

Document configuration, with screenshots. Cover the following
- search api config
- indexing
- search view mode
- facets
- 
## Definition of done (DoD)

- [ ] Developer with no knowledge of the system can follow the instructions and get search working

>**Note**: All documentation in the wiki are considered _living documents_ and will be changed as needed after this task has been completed.

**Comment by NicoledeGreef** [comment]
Is there a link or file to review?

**Comment by CraigClark** [comment]
@NicoledeGreef Link is here https://github.com/bcgov/bcbb/wiki/search

I'm going to move this to 'working on it'. It needs more screeshots

**Comment by CraigClark** [comment]
@NicoledeGreef ready for your review

**Comment by CraigClark** [comment]
Adding sprint 2 tag so his gets reviewed.

**Comment by NicoledeGreef** [comment]
Thanks @CraigClark 

Without actually running the instructions myself, I just found one thing:

"Note: while you are working with the content section of the **varant**, you will see regions Top, Left and Right. These are the regions as displayed on the search results page. Moving blocks between regions will affect where they display on the search page."

I think it should be "variant".  I can edit the wiki so I will make the change and other minor ones.
